#!/usr/bin/env python
import rospy
from sensor_msgs.msg import PointCloud2
import numpy as np
import sys

def sender():
    rospy.init_node('pc_sender')
    print("reading")
    msg = PointCloud2()
    with open('/home/senft/pc2.txt', 'r') as infile:
        msg.deserialize(infile.read())
    msg.header.frame_id = 'static_camera_link'
    pub = rospy.Publisher("/static_points2",PointCloud2, queue_size =1, latch = True)
    pub.publish(msg)
    rospy.spin()

if __name__ == '__main__':
    sender()


