#!/usr/bin/env python
import numpy as np
import math
import rospy
import signal
import sys
from geometry_msgs.msg import PoseStamped, PoseArray
from authoring_msgs.msg import POI, POIArray
import tf
import copy

REFERENCE_FRAME='panda_link0'

class Poi(object):
    def __init__(self):
        self._pois_pub = rospy.Publisher("/pois",POIArray,queue_size=1,latch=True)
        self._poses_pub = rospy.Publisher("/pois_pose",PoseArray,queue_size=1,latch=True)
        self.publish_pois()
        
    def publish_pois(self):
        array = POIArray()
        
        #POI1
        poi_init = POI()
        poi_init.pose.pose.position.x=.463
        poi_init.pose.pose.position.y=-.277
        poi_init.pose.pose.position.z=.063
        poi_init.pose.pose.orientation.w=1
        poi_init.pose.header.frame_id = REFERENCE_FRAME
        poi_init.type = poi_init.SCREW
        poi_init.id = 0
        array.poi_array.append(poi_init)
        for i in range(4):
            poi = copy.deepcopy(poi_init)
            poi.pose.pose.position.x+=(i+1)*0.0375
            poi.id = i+1
            array.poi_array.append(poi)
        for i in range(5):
            for j in range(5):
                poi = copy.deepcopy(poi_init)
                poi.pose.pose.position.x+=-.197+.036*i
                poi.pose.pose.position.y+=-.001+.04*j
                poi.pose.pose.position.z+=.003
                poi.id = j+5*i
                poi.type = poi.HOLE
                array.poi_array.append(poi)

        poi = copy.deepcopy(poi_init)
        poi.type = poi.SCREW_DRIVER
        #poi5.pose.pose.position.x = -0.045
        #poi5.pose.pose.position.y = 0.340
        #poi5.pose.pose.position.z = -0.169
        poi.pose.pose.position.x += .19
        #poi.pose.pose.position.y = -0.281
        poi.pose.pose.position.z += .094
        array.poi_array.append(poi)

        self._pois_pub.publish(array)

        pose_array = PoseArray()
        pose_array.header.frame_id = REFERENCE_FRAME
        for poi in array.poi_array:
            pose_array.poses.append(poi.pose.pose)
        self._poses_pub.publish(pose_array)


    def run(self):
        rospy.spin()

    def signal_handler(self, signal, frame):
        sys.exit()

if __name__ == "__main__":
    rospy.init_node('poi')
    poi = Poi()
    signal.signal(signal.SIGINT, poi.signal_handler)
    poi.run()
