#!/usr/bin/env python
import numpy as np
import math
import rospy
import signal
import sys
from std_msgs.msg import String, ColorRGBA
from visualization_msgs.msg import Marker
from geometry_msgs.msg import PoseStamped, Point, Pose, PoseArray, Quaternion, Twist, TransformStamped
from authoring_msgs.msg import Action, Command, POI, POIArray
from pose_detector.msg import DetectedObject,DetectedObjects
import tf
import tf2_ros
import tf2_geometry_msgs
import copy
from threading import Timer
from tf.transformations import quaternion_from_euler, euler_from_quaternion

REFERENCE_FRAME='panda_link0'
CAMERA_FRAME='external_rgb_camera_link'

class Tracker(object):
    def __init__(self):
        self._tfBuffer = tf2_ros.Buffer()
        self._tl = tf2_ros.TransformListener(self._tfBuffer)
        rospy.sleep(0.5) # sleep a bit to make sure the TF cache is filled

        self._br = tf2_ros.TransformBroadcaster()
        rospy.sleep(.5)

        self._poi_pub = rospy.Publisher("/world_state/pois", POIArray, queue_size=1, latch=True)
        self._marker_pub = rospy.Publisher("/viz/meshes", Marker, queue_size=1)

        self._init_pois = None
        self._objects = []
        self._moving = False
        self._moving_timer = None

        self._grasped_object = None
        self._sim = False

        self._cmd = None
        self._tf_array = []

        self._age_threshold = 3

        self._poi_sub = rospy.Subscriber("pois", POIArray, self.on_pois, queue_size = 1)
        self._gui_sub = rospy.Subscriber("parser/command", Command, self.on_command, queue_size = 1)
        self._event_sub = rospy.Subscriber("event", String, self.on_event, queue_size = 1)
        self._object_sub = rospy.Subscriber("/detected_objects", DetectedObjects, self.on_objects)
        self._simulated_objects_sub = rospy.Subscriber("/simulated_objects", POIArray, self.on_simulated_objects)

    def get_diff_poses(self, p1, p2):
        return np.sqrt((p1.position.x-p2.position.x)**2+(p1.position.y-p2.position.y)**2+(p1.position.z-p2.position.z)**2)

    def get_poi_from_object(self, o):
        pose = PoseStamped()
        pose.header.frame_id = "internal_rgb_camera_link"
        pose.pose = o.pose
        pose = self._tfBuffer.transform(pose,REFERENCE_FRAME)
        pose.pose.position.z+=.03
        q = [pose.pose.orientation.x,pose.pose.orientation.y,pose.pose.orientation.z,pose.pose.orientation.w]
        e = euler_from_quaternion(q)
        q = quaternion_from_euler(0,0,e[2])
        #pose.pose.orientation.x = q[0]
        #pose.pose.orientation.y = q[1]
        #pose.pose.orientation.z = q[2]
        #pose.pose.orientation.w = q[3]
        pose.pose.orientation.x = 0
        pose.pose.orientation.y = 0
        pose.pose.orientation.z = 0
        pose.pose.orientation.w = 1
        poi = POI()
        poi.type = o.mesh_name
        poi.pose = pose
        return poi

    def update_poi(self, p1, p2):
        p1.position.x=(p1.position.x+p2.position.x)/2
        p1.position.y=(p1.position.y+p2.position.y)/2
        p1.position.z=(p1.position.z+p2.position.z)/2

    def testFilter(self,o,newPois,minX,maxX,minY,maxY):
        if not (o.pose.pose.position.x>minX and o.pose.pose.position.x<maxX and o.pose.pose.position.y>minY and o.pose.pose.position.y<maxY):
                return True
        toKeep = False
        for poi in newPois:
            if self.get_diff_poses(o.pose.pose, poi.pose.pose) < .02:
                toKeep = True
        return toKeep            
    
    def on_objects(self, msg):
        if self._moving or self._sim:
            return
        minX=np.inf
        maxX=-np.inf
        minY=np.inf
        maxY=-np.inf
        for o in self._objects:
            #print("id "+str(o.id))
            #print(o.age)
            if o.age > 0:
                o.age -= 1

        for new_o in msg.detected_objects:
            poi = self.get_poi_from_object(new_o)
            minX = min(minX,poi.pose.pose.position.x)
            maxX = max(maxX,poi.pose.pose.position.x)
            minY = min(minY,poi.pose.pose.position.y)
            maxY = max(maxY,poi.pose.pose.position.y)
            poi.id = 0
            for known_poi in self._objects:
                if poi.type == known_poi.type:
                    poi.id+=1
                    if self.get_diff_poses(known_poi.pose.pose, poi.pose.pose) < .02:
                        self.update_poi(known_poi.pose.pose,poi.pose.pose)
                        if known_poi.age<252:
                            known_poi.age += 2
                        break
            else:
                print("new object")
                poi.age = 1
                self._objects.append(poi)
        #self._objects[:] = [o for o in self._objects if self.testFilter(o,newPois,minX,maxX,minY,maxY)]
        #self._objects = newPois
        

    def on_pois(self, msg):
        if self._init_pois is not None:
            return
        self._init_pois = []
        for p in msg.poi_array:
            p.age = self._age_threshold
            self._init_pois.append(p)
        self.publish_pois()

    def on_simulated_objects(self, msg):
        for p in msg.poi_array:
            self._objects.append(p)

    def on_command(self, msg):
        self._cmd = msg

    def reset_moving(self):
        self._moving = False
        self._moving_timer = None

    def on_event(self, msg):
        event = msg.data.split(';')
        if event[0] == "start_sim":
            self._sim = True
        if event[0] == "grasped":
            self._grasped_object = event[1]
            print("grasping "+self._grasped_object)
        if event[0] == "released":
            self._grasped_object = None

        if event[0] == "start_exec":
            self._moving = True
            if self._moving_timer is not None:
                self._moving_timer.cancel()
                self._moving_timer = None
        if event[0] == "motion_finished":
            self._moving_timer = Timer(1.0, self.reset_moving)
            self._moving_timer.start()
            if self._sim:
                self._sim = False
                self._grasped_object = None
            
            self.publish_pois()

    def get_transform(self, poi):
        if self.get_name(poi) == self._grasped_object:
            t = self._tfBuffer.lookup_transform(REFERENCE_FRAME, 'sim_end_effector', rospy.Time(0))
            poi.pose.header.frame_id = REFERENCE_FRAME
            poi.pose.pose.position = self.get_pose_from_trans(t).position
            poi.age = 20
        t = TransformStamped()
        t.header.frame_id = poi.pose.header.frame_id
        t.child_frame_id = self.get_name(poi)
        t.header.stamp = rospy.Time.now()
        t.transform.translation.x=poi.pose.pose.position.x
        t.transform.translation.y=poi.pose.pose.position.y
        t.transform.translation.z=poi.pose.pose.position.z
        t.transform.rotation.x=poi.pose.pose.orientation.x
        t.transform.rotation.y=poi.pose.pose.orientation.y
        t.transform.rotation.z=poi.pose.pose.orientation.z
        t.transform.rotation.w=poi.pose.pose.orientation.w
        index = -1
        d = np.inf

        if poi.type.data == "screw" and self.get_name(poi) != self._grasped_object:
            for i,p in enumerate(self._init_pois):
                if p.type.data == "hole":
                    temp_d = self.get_diff_poses(poi.pose.pose,p.pose.pose) 
                    if temp_d < d:
                        d = temp_d
                        index = i
                        
        if d < .04:
            t.transform.translation.x = self._init_pois[index].pose.pose.position.x
            t.transform.translation.y = self._init_pois[index].pose.pose.position.y
        return t   

    def publish_pois(self):
        if self._init_pois is None:
            return
        self._tf_array = []
        msg = POIArray()
        for poi in self._init_pois+self._objects:
            if poi.age < self._age_threshold:
                continue
            poi.pose.header.stamp = rospy.Time(0)

            t = self.get_transform(poi)
            self._tf_array.append(t)
            msg.poi_array.append(poi)
        self._poi_pub.publish(msg)
        self._br.sendTransform(self._tf_array)
           
    def get_pose_from_trans(self, t):
        pose = Pose()
        pose.position.x = t.transform.translation.x
        pose.position.y = t.transform.translation.y
        pose.position.z = t.transform.translation.z
        pose.orientation.x = t.transform.rotation.x
        pose.orientation.y = t.transform.rotation.y
        pose.orientation.z = t.transform.rotation.z
        pose.orientation.w = t.transform.rotation.w
        return pose

    #def publish_meshes(self):
    #    for p in self._estimated_objects:
    #        if self.get_name(p) == self._grasped_object:
    #            t = self._tfBuffer.lookup_transform(REFERENCE_FRAME, 'sim_end_effector', rospy.Time(0))
    #            p.pose.header.frame_id = REFERENCE_FRAME
    #            p.pose.pose = self.get_pose_from_trans(t)
    #            
    #        if p.type.data == "screw":
    #            self.publish_mesh(p.pose.pose, "screw", p.id, "#a9a9a9",.70)


    #from https://stackoverflow.com/questions/29643352/converting-hex-to-rgb-value-in-python
    def get_color(self, string, alpha):
        color = ColorRGBA()
        string=string.lstrip('#')
        (r,g,b) = tuple(int(string[i:i+2], 16)/255. for i in (0, 2, 4))
        color.r = r
        color.g = g
        color.b = b
        color.a=alpha
        return color


    def get_name(self, poi):
        return poi.type.data + '_' + str(poi.id)

    def publish_mesh(self, pose, name, i, color, alpha):
        marker = Marker()
        marker.header.frame_id = REFERENCE_FRAME
        marker.pose = copy.deepcopy(pose)
        marker.pose.position.z-=.053
        marker.ns = name
        marker.id = i
        scale = 1
        marker.scale.x=scale
        marker.scale.y=scale
        marker.scale.z=scale
        marker.color = self.get_color(color, alpha)
        marker.type = marker.MESH_RESOURCE
        marker.mesh_resource = "package://authoring/meshes/"+name+".stl"
        self._marker_pub.publish(marker)

    def run(self):
        r = rospy.Rate(20)
        while not rospy.is_shutdown():
            #self.publish_meshes()
            self.publish_pois()
            r.sleep()

    def signal_handler(self, signal, frame):
        sys.exit()

if __name__ == "__main__":
    rospy.init_node('state_tracker')
    tracker = Tracker()
    signal.signal(signal.SIGINT, tracker.signal_handler)
    tracker.run()
